language: generic
sudo: required
services:
  - docker
  - xvfb
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - docker build -t prashitprakhar/docker-angular-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prashitprakhar/docker-angular-test npm run e2e

after_success:
  - docker build -t prashitprakhar/multi-client ./client
  - docker build -t prashitprakhar/multi-nginx ./nginx
  - docker build -t prashitprakhar/multi-server ./server
  - docker build -t prashitprakhar/multi-worker ./worker
  # Log In to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # TAKE ALL IMAGES AND PUSH TO DOCKER.HUB
  - docker push prashitprakhar/multi-client
  - docker push prashitprakhar/multi-nginx
  - docker push prashitprakhar/multi-server
  - docker push prashitprakhar/multi-worker